import Mathlib.Topology.Basic
import Mathlib.Topology.Maps.Basic
import Mathlib.Tactic.FunProp
import Mathlib.Data.Setoid.Basic
import EquivVerification.Common
import EquivVerification.Equiv

/-!
# No-Drift for Functor Models

For artifacts with a common observable interface `X → Y`, semantic equivalence on
parameters is observational equivalence of realized functions. A committed update
is a continuous parameter map that preserves evaluation semantics pointwise.

The main theorem shows that such an update preserves and reflects semantic
equivalence exactly, hence induces a well-defined map on semantic quotients.
-/

namespace EquivVerification.NoDrift

open EquivVerification.Common

universe u v w

/-- An artifact with parameter space `Θ` and evaluation semantics into `X → Y`. -/
structure Artifact (X : Type u) (Y : Type v) where
  Θ : Type w
  topology : TopologicalSpace Θ
  eval : Θ → X → Y

attribute [instance] Artifact.topology

/--
`Θ(M)` in the paper: the parameter space of the artifact `M`.

This is only a lightweight alias for presentation; the underlying data is still
stored in the field `M.Θ`.
-/
abbrev ThetaSpace {X : Type u} {Y : Type v} (M : Artifact X Y) := M.Θ

/-- Semantic equivalence is observational equivalence of realized functions. -/
def SemanticEquiv {X : Type u} {Y : Type v} (M : Artifact X Y) : M.Θ → M.Θ → Prop :=
  ObservationalEquivalence M.eval

/-- Setoid generated by semantic equivalence. -/
def semanticSetoid {X : Type u} {Y : Type v} (M : Artifact X Y) : Setoid M.Θ where
  r := SemanticEquiv M
  iseqv := observational_equivalence_is_equivalence M.eval

/-- Quotient of parameters modulo semantic equivalence. -/
def SemanticQuotient {X : Type u} {Y : Type v} (M : Artifact X Y) :=
  Quotient (semanticSetoid M)

/--
`Θ_sem(M)` in the paper: the semantic quotient of the parameter space.

This is a presentation alias for `SemanticQuotient`.
-/
abbrev ThetaSem {X : Type u} {Y : Type v} (M : Artifact X Y) := SemanticQuotient M

/--
`q_M` in the paper: the canonical projection from parameters to semantic classes.

This is the quotient projection sending a parameter to its semantic equivalence
class.
-/
def q {X : Type u} {Y : Type v} (M : Artifact X Y) : ThetaSpace M → ThetaSem M :=
  Quotient.mk''

@[simp]
theorem q_apply {X : Type u} {Y : Type v} (M : Artifact X Y) (θ : ThetaSpace M) :
    q M θ = Quotient.mk'' θ := rfl

/-- A committed update is a continuous parameter map preserving semantics pointwise. -/
structure CommittedUpdate {X : Type u} {Y : Type v} (M₁ M₂ : Artifact X Y) where
  f : M₁.Θ → M₂.Θ
  continuous : Continuous f
  semantics_preserving : ∀ θ x, M₂.eval (f θ) x = M₁.eval θ x

/--
Identity committed update.

This is the neutral element for commit composition and represents a commit step
that leaves both parameters and semantics unchanged.
-/
def id_semantics_preserving {X : Type u} {Y : Type v} (M : Artifact X Y) :
    CommittedUpdate M M :=
  { f := id
    continuous := continuous_id
    semantics_preserving := by
      intro θ x
      rfl }

/--
Composition of committed updates.

If `f : M₁ → M₂` and `g : M₂ → M₃` are semantics-preserving committed updates,
then their composition is again a semantics-preserving committed update.
-/
def comp_semantics_preserving {X : Type u} {Y : Type v}
    {M₁ M₂ M₃ : Artifact X Y}
    (f : CommittedUpdate M₁ M₂) (g : CommittedUpdate M₂ M₃) :
    CommittedUpdate M₁ M₃ :=
  { f := g.f ∘ f.f
    continuous := g.continuous.comp f.continuous
    semantics_preserving := by
      intro θ x
      calc
        M₃.eval (g.f (f.f θ)) x = M₂.eval (f.f θ) x := g.semantics_preserving (f.f θ) x
        _ = M₁.eval θ x := f.semantics_preserving θ x }

/--
Liftability to the semantic quotient: semantically equivalent source parameters
map to semantically equivalent target parameters.
-/
def IsLiftable {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) : Prop :=
  ∀ ⦃θ₁ θ₂ : M₁.Θ⦄, SemanticEquiv M₁ θ₁ θ₂ → SemanticEquiv M₂ (upd.f θ₁) (upd.f θ₂)

/-- Pointwise semantic preservation implies quotient liftability. -/
theorem isLiftable_of_semantics_preserving {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) :
    IsLiftable upd := by
  intro θ₁ θ₂ h
  unfold SemanticEquiv at h ⊢
  ext x
  calc
    M₂.eval (upd.f θ₁) x = M₁.eval θ₁ x := upd.semantics_preserving θ₁ x
    _ = M₁.eval θ₂ x := congrArg (fun g => g x) h
    _ = M₂.eval (upd.f θ₂) x := (upd.semantics_preserving θ₂ x).symm

/-- The induced map on semantic quotient classes. -/
def mapSemanticQuotient {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) :
    SemanticQuotient M₁ → SemanticQuotient M₂ :=
  Quotient.map upd.f (by
    intro θ₁ θ₂ h
    exact isLiftable_of_semantics_preserving upd h)

@[simp]
theorem mapSemanticQuotient_mk {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) (θ : M₁.Θ) :
    mapSemanticQuotient upd (Quotient.mk'' θ) = Quotient.mk'' (upd.f θ) := rfl

/--
Lift a committed update to the semantic quotient.

This is the descended map `\bar f` from the paper: because committed updates are
liftable, they act on semantic equivalence classes.
-/
def liftToQuotient {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) :
    SemanticQuotient M₁ → SemanticQuotient M₂ :=
  mapSemanticQuotient upd

@[simp]
theorem liftToQuotient_mk {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) (θ : M₁.Θ) :
    liftToQuotient upd (Quotient.mk'' θ) = Quotient.mk'' (upd.f θ) := rfl

/--
The quotient lift commutes with the canonical projection:

`bar f ∘ q = q ∘ f`.
-/
theorem lift_commutes {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) :
    ∀ θ : M₁.Θ,
      liftToQuotient upd (Quotient.mk'' θ) = Quotient.mk'' (upd.f θ) := by
  intro θ
  rfl

/--
No semantic drift: the update preserves and reflects semantic equivalence exactly.

Paper interpretation: this is exact preservation and reflection of semantic
equivalence for a single committed update.
-/
theorem no_semantic_drift {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) :
    ∀ θ₁ θ₂ : M₁.Θ, SemanticEquiv M₁ θ₁ θ₂ ↔ SemanticEquiv M₂ (upd.f θ₁) (upd.f θ₂) := by
  intro θ₁ θ₂
  constructor
  · intro h
    exact isLiftable_of_semantics_preserving upd h
  · intro h
    unfold SemanticEquiv at h ⊢
    ext x
    calc
      M₁.eval θ₁ x = M₂.eval (upd.f θ₁) x := (upd.semantics_preserving θ₁ x).symm
      _ = M₂.eval (upd.f θ₂) x := congrArg (fun g => g x) h
      _ = M₁.eval θ₂ x := upd.semantics_preserving θ₂ x

/--
No drift on semantic quotients.

The descended map on quotient classes is well-defined, and source classes are
equal exactly when their images are equal.

Paper interpretation: this is the well-defined and injective behavior of `f̄`
on the semantic quotient.
-/
theorem no_drift_on_quotients {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) :
    ∀ θ₁ θ₂ : M₁.Θ,
      liftToQuotient upd (Quotient.mk'' θ₁) = liftToQuotient upd (Quotient.mk'' θ₂) ↔
        Quotient.mk'' θ₁ = (Quotient.mk'' θ₂ : SemanticQuotient M₁) := by
  intro θ₁ θ₂
  constructor
  · intro h
    have h' : SemanticEquiv M₂ (upd.f θ₁) (upd.f θ₂) := by
      exact Quotient.exact h
    exact Quotient.sound ((no_semantic_drift upd θ₁ θ₂).mpr h')
  · intro h
    exact congrArg (liftToQuotient upd) h

/--
The quotient action of a committed update is injective on semantic classes.

This is the quotient-level form of exact no-drift.
-/
theorem liftToQuotient_injective {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) :
    Function.Injective (liftToQuotient upd) := by
  intro a b h
  refine Quotient.inductionOn₂ a b ?_ h
  intro θ₁ θ₂ hEq
  exact (no_drift_on_quotients upd θ₁ θ₂).mp hEq

/-!
## Chain-level governed no-drift

The theorem `no_semantic_drift` above is the exact single-update result: a
pointwise semantics-preserving committed update cannot introduce semantic drift.

The definitions below add a second, more document-faithful layer:

- commit chains model commit composition directly;
- `ContractChanging` marks updates that are explicitly allowed to change enforced
  behavior;
- `KStable` is kept abstract here as a lightweight governance predicate;
- chain theorems show that if no step is contract-changing, semantic equivalence
  is preserved end-to-end.

This matches the intended reading of the document-level theorem in a
compile-safe way: contract-changing steps are the only permitted source of
semantic change along a governed chain.
-/

/-- Simple composable commit chains between artifacts with fixed observable types. -/
inductive CommitChain {X : Type u} {Y : Type v} :
    Artifact X Y → Artifact X Y → Sort _ where
  | nil (M : Artifact X Y) : CommitChain M M
  | cons {M₁ M₂ M₃ : Artifact X Y} :
      CommittedUpdate M₁ M₂ → CommitChain M₂ M₃ → CommitChain M₁ M₃

namespace CommitChain

/-- End-to-end committed update obtained by composing a commit chain. -/
def toCommittedUpdate {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y} :
    CommitChain M₁ M₂ → CommittedUpdate M₁ M₂
  | nil M =>
      id_semantics_preserving M
  | cons upd tail =>
      let tailUpd := toCommittedUpdate tail
      comp_semantics_preserving upd tailUpd

/-- The end-to-end parameter map of a commit chain. -/
def map {X : Type u} {Y : Type v} {M₁ M₂ : Artifact X Y} (chain : CommitChain M₁ M₂) :
    M₁.Θ → M₂.Θ :=
  (toCommittedUpdate chain).f

@[simp]
theorem toCommittedUpdate_nil {X : Type u} {Y : Type v} (M : Artifact X Y) :
    toCommittedUpdate (nil M) = id_semantics_preserving M := rfl

@[simp]
theorem toCommittedUpdate_cons {X : Type u} {Y : Type v}
    {M₁ M₂ M₃ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) (tail : CommitChain M₂ M₃) :
    toCommittedUpdate (cons upd tail) =
      comp_semantics_preserving upd (toCommittedUpdate tail) := rfl

@[simp]
theorem map_nil {X : Type u} {Y : Type v} (M : Artifact X Y) :
    map (nil M) = id := by
  rfl

@[simp]
theorem map_cons {X : Type u} {Y : Type v}
    {M₁ M₂ M₃ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) (tail : CommitChain M₂ M₃) :
    map (cons upd tail) = map tail ∘ upd.f := by
  rfl

/-- Universal quantification over the steps of a commit chain. -/
def All {X : Type u} {Y : Type v}
    (P : ∀ {A B : Artifact X Y}, CommittedUpdate A B → Prop)
    {M₁ M₂ : Artifact X Y} : CommitChain M₁ M₂ → Prop
  | nil _ => True
  | cons upd tail => P upd ∧ All P tail

/-- Existential quantification over the steps of a commit chain. -/
def Any {X : Type u} {Y : Type v}
    (P : ∀ {A B : Artifact X Y}, CommittedUpdate A B → Prop)
    {M₁ M₂ : Artifact X Y} : CommitChain M₁ M₂ → Prop
  | nil _ => False
  | cons upd tail => P upd ∨ Any P tail

/--
End-to-end exact no-drift for a chain of semantics-preserving committed updates.

This is the chain version of `no_semantic_drift`, obtained by composing the
chain into a single committed update.
-/
theorem no_semantic_drift {X : Type u} {Y : Type v} {M₀ Mₙ : Artifact X Y}
    (chain : CommitChain M₀ Mₙ) :
    ∀ θ₁ θ₂ : M₀.Θ,
      SemanticEquiv M₀ θ₁ θ₂ ↔
        SemanticEquiv Mₙ (chain.map θ₁) (chain.map θ₂) := by
  simpa [map] using
    (EquivVerification.NoDrift.no_semantic_drift (toCommittedUpdate chain))

/--
Inductive chain proof of no-drift.

This mirrors the paper’s step-by-step commit-chain reasoning rather than relying
only on collapse to a single composed update.

Paper interpretation: no drift across commit chains.
-/
theorem chain_no_drift_inductive {X : Type u} {Y : Type v} {M₀ Mₙ : Artifact X Y}
    (chain : CommitChain M₀ Mₙ) :
    ∀ θ₁ θ₂ : M₀.Θ,
      SemanticEquiv M₀ θ₁ θ₂ ↔
        SemanticEquiv Mₙ (chain.map θ₁) (chain.map θ₂) := by
  induction chain with
  | nil M =>
      intro θ₁ θ₂
      simp [map, toCommittedUpdate, id_semantics_preserving]
  | @cons M₁ M₂ M₃ upd tail ih =>
      intro θ₁ θ₂
      simp only [map_cons, Function.comp_apply]
      constructor
      · intro h
        have h₁ : SemanticEquiv M₂ (upd.f θ₁) (upd.f θ₂) :=
          (EquivVerification.NoDrift.no_semantic_drift upd θ₁ θ₂).mp h
        exact (ih (upd.f θ₁) (upd.f θ₂)).mp h₁
      · intro h
        have h₁ : SemanticEquiv M₂ (upd.f θ₁) (upd.f θ₂) :=
          (ih (upd.f θ₁) (upd.f θ₂)).mpr h
        exact (EquivVerification.NoDrift.no_semantic_drift upd θ₁ θ₂).mpr h₁

/-- If not every step is non-contract-changing, then some step is contract-changing. -/
theorem any_of_not_all_not {X : Type u} {Y : Type v}
    (P : ∀ {A B : Artifact X Y}, CommittedUpdate A B → Prop)
    {M₀ Mₙ : Artifact X Y} (chain : CommitChain M₀ Mₙ) :
    ¬ All (fun upd => ¬ P upd) chain → Any P chain := by
  induction chain with
  | nil M =>
      intro h
      simp [All] at h
  | @cons M₁ M₂ M₃ upd tail ih =>
      intro h
      by_cases hp : P upd
      · exact Or.inl hp
      · apply Or.inr
        apply ih
        intro htail
        exact h ⟨hp, htail⟩

end CommitChain

/-- Lightweight abstract predicate marking updates that explicitly change contract. -/
abbrev ContractChangingPred (X : Type u) (Y : Type v) :=
  EquivVerification.Common.ContractChangingPred (fun A B : Artifact X Y => CommittedUpdate A B)

/--
Lightweight abstract predicate expressing K-stability of updates.

Intended connection to `KStable.lean`: K-stability is meant to capture
invariant preservation at the observable / K-theoretic level.
-/
abbrev KStablePred (X : Type u) (Y : Type v) :=
  EquivVerification.Common.KStablePred (fun A B : Artifact X Y => CommittedUpdate A B)

/--
Governance condition for a committed update:

- either it is liftable or it is explicitly marked contract-changing;
- if it is not contract-changing, then it is K-stable.

In the present file, `CommittedUpdate` already carries the stronger
pointwise semantic preservation property, so liftability is derivable.
This definition keeps the document-level governance layer explicit.
-/
def GovernedBy {X : Type u} {Y : Type v} (ContractChanging : ContractChangingPred X Y)
    (KStable : KStablePred X Y) {M₁ M₂ : Artifact X Y}
    (upd : CommittedUpdate M₁ M₂) : Prop :=
  EquivVerification.Common.GovernedBy
    (fun {A B} (u : CommittedUpdate A B) => IsLiftable u)
    ContractChanging
    KStable
    upd

/--
Under governance, a non-contract-changing update must be liftable.

This is the single-step governance lemma corresponding to the document’s
“either liftable or explicitly contract-changing” clause.
-/
theorem isLiftable_of_governed_non_contractChanging {X : Type u} {Y : Type v}
    (ContractChanging : ContractChangingPred X Y) (KStable : KStablePred X Y)
    {M₁ M₂ : Artifact X Y} (upd : CommittedUpdate M₁ M₂)
    (hgov : GovernedBy ContractChanging KStable upd)
    (hnot : ¬ ContractChanging upd) :
    IsLiftable upd := by
  rcases hgov.1 with hlift | hchange
  · exact hlift
  · exact False.elim (hnot hchange)

/--
Document-faithful chain theorem, specialized to the current stronger update model:
if every step in the chain is non-contract-changing, then semantic equivalence is
preserved end-to-end.

The governance and K-stability assumptions are included to mirror the document.
The proof uses the stronger fact already built into `CommittedUpdate`: each step is
pointwise semantics-preserving, hence the whole chain is exactly no-drift.
-/
theorem chain_no_semantic_drift_of_all_non_contractChanging {X : Type u} {Y : Type v}
    (ContractChanging : ContractChangingPred X Y) (KStable : KStablePred X Y)
    {M₀ Mₙ : Artifact X Y} (chain : CommitChain M₀ Mₙ)
    (_hgov : CommitChain.All (fun upd => GovernedBy ContractChanging KStable upd) chain)
    (_hnoChange : CommitChain.All (fun upd => ¬ ContractChanging upd) chain) :
    ∀ θ₁ θ₂ : M₀.Θ,
      SemanticEquiv M₀ θ₁ θ₂ ↔
        SemanticEquiv Mₙ (chain.map θ₁) (chain.map θ₂) := by
  intro θ₁ θ₂
  exact CommitChain.no_semantic_drift chain θ₁ θ₂

/--
If an end-to-end semantic change is observed, then the chain cannot consist solely
of non-contract-changing steps.

This is a precise governed no-drift statement: semantic change requires an
explicitly governed contract-changing update somewhere in the chain.
-/
theorem semantic_change_requires_contract_change {X : Type u} {Y : Type v}
    (ContractChanging : ContractChangingPred X Y) (KStable : KStablePred X Y)
    {M₀ Mₙ : Artifact X Y} (chain : CommitChain M₀ Mₙ)
    (hgov : CommitChain.All (fun upd => GovernedBy ContractChanging KStable upd) chain)
    {θ₁ θ₂ : M₀.Θ}
    (hchange :
      ¬ (SemanticEquiv M₀ θ₁ θ₂ ↔
          SemanticEquiv Mₙ (chain.map θ₁) (chain.map θ₂))) :
    ¬ CommitChain.All (fun upd => ¬ ContractChanging upd) chain := by
  intro hnoChange
  exact hchange (chain_no_semantic_drift_of_all_non_contractChanging
    ContractChanging KStable chain hgov hnoChange θ₁ θ₂)

/--
Finite-chain existence form of governed no-drift:
if end-to-end semantic change occurs, some update in the chain must be explicitly
marked contract-changing.

Paper interpretation: semantic change requires explicit contract change.
-/
theorem semantic_change_implies_some_contract_change {X : Type u} {Y : Type v}
    (ContractChanging : ContractChangingPred X Y) (KStable : KStablePred X Y)
    {M₀ Mₙ : Artifact X Y} (chain : CommitChain M₀ Mₙ)
    (hgov : CommitChain.All (fun upd => GovernedBy ContractChanging KStable upd) chain)
    {θ₁ θ₂ : M₀.Θ}
    (hchange :
      ¬ (SemanticEquiv M₀ θ₁ θ₂ ↔
          SemanticEquiv Mₙ (chain.map θ₁) (chain.map θ₂))) :
    CommitChain.Any (fun upd => ContractChanging upd) chain := by
  apply CommitChain.any_of_not_all_not (P := fun upd => ContractChanging upd) chain
  exact semantic_change_requires_contract_change ContractChanging KStable chain hgov hchange

end EquivVerification.NoDrift
